### ISSUE TITLE
Методика испытаний

### ISSUE THREAD

**Issue by zhenyatos** [zhenyatos/pytux#20]
Добавить в документацию:
- [x] алфавит т.е. описание множества допустимых символов языка
- [x] контекстные условия т.е. синтаксические правила которые неудобно выражать в КСГ
- [x] 1 сложный пример, транслируемый без ошибок
- [x] 3 простых примера, в которых присутствуют синтаксические ошибки с пояснением
- [x] КАРТИНКИИИИИ

**Comment by via8** [comment]
Documentation 1st version:
[report.pdf](https://github.com/via8/pytux/files/6150583/report.pdf)

**Comment by zhenyatos** [comment]
FUCK, FUCK, FUCK
Why did you use - instead of -- in LaTeX? It is really important, you moron. FFFFFUCK.
...
FUCK.

**Comment by via8** [comment]
Documentation 2nd version (notes taken into account):
[report-v2.pdf](https://github.com/via8/pytux/files/6151333/report-v2.pdf)

**Comment by zhenyatos** [comment]
Nice cock.
